### Site Settings ###
title               : Evgenii Bazhanov
description         : >-                               # >- means to ignore newlines until "url:"
  Passionate Front End developer with love for React, 
  JavaScript, TypeScript, Blockchain. I enjoy clean, 
  semantic, well-documented 
  and testable code.

url                 : ""                                   # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                                   # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : ebazhanov/ebazhanov.github.io  # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2 # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Evgenii Bazhanov
  image             : /assets/foto.jpg
# behance           : your_username
# dribbble          : your_username
# email             : username@domain.com
# facebook          : your_username
  github            : ebazhanov
# gitlab            : your_username
# instagram         : your_username
  linkedin          : ebazhanov
  medium            : zhenja
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 9438913
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : EvgenyBazhanov
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"

### Posts Permalink ###
permalink: blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
